In [1]:
import pandas as pd

# nr

In [2]:
from processing import National

In [3]:
nr = National()

## 2002

In [4]:
df_02 = pd.read_excel('data/nrsr/nrsr2002.xls')

In [5]:
df_02.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,Počet,Platné hlasy (počet/podiel),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\nOkres,platných\nhlasov\n spolu,SZS,SDKÚ,SDPO,SDĽ,SMER,HZDS,OKS,HZD,...,ANO,B-RRS,ŽAR,SDA,SNJ,NOSP,SNS,ROSA,ROISR,P SNS
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bratislava I,30501,258,12400,23,296,2707,3539,356,852,...,1639,10,71,946,39,93,929,19,1,325
4,NaN,NaN,0.84,40.65,0.07,0.97,8.87,11.6,1.16,2.79,...,5.37,0.03,0.23,3.1,0.12,0.3,3.04,0.06,0,1.06

In [6]:
df_02 = nr.preprocess_2002(df_02)

In [7]:
df_02 = nr.set_header_and_clean(df_02)

In [8]:
df_02 = nr.add_foreign(df_02)

In [9]:
df_02.head()

,Okres,platných hlasov spolu,SZS,SDKÚ,SDPO,SDĽ,SMER,HZDS,OKS,HZD,...,ANO,B-RRS,ŽAR,SDA,SNJ,NOSP,SNS,ROSA,ROISR,P SNS
0,Bratislava I,30501,258,12400,23,296,2707,3539,356,852,...,1639,10,71,946,39,93,929,19,1,325
1,Bratislava II,66134,586,22222,82,639,7737,8992,415,1997,...,4434,29,252,1832,61,207,2404,67,24,1053
2,Bratislava III,39825,388,13209,42,394,4889,5913,312,1256,...,2734,12,141,1092,64,153,1569,60,5,800
3,Bratislava IV,55082,505,20036,71,522,7196,6278,446,1611,...,4383,18,270,1739,74,208,1775,75,11,872
4,Bratislava V,72225,808,25795,84,746,9921,7467,554,1972,...,5816,29,396,2378,79,220,2413,80,21,1541

In [10]:
df_02.shape

(81, 27)

In [11]:
nr.process_2002(df_02)

In [12]:
df_test = nr.df

In [13]:
df_test.head()

,election_year,election_type,district_id,district_name,total_district_votes,original_party_name,party_name,votes
0,2002,NR SR,<NA>,Bratislava I,30501,SZS,SZS,258
1,2002,NR SR,<NA>,Bratislava II,66134,SZS,SZS,586
2,2002,NR SR,<NA>,Bratislava III,39825,SZS,SZS,388
3,2002,NR SR,<NA>,Bratislava IV,55082,SZS,SZS,505
4,2002,NR SR,<NA>,Bratislava V,72225,SZS,SZS,808

## 2006

In [14]:
df_06 = pd.read_excel('data/nrsr/nrsr2006.xls')