In [3]:
import pandas as pd

# nr

In [4]:
from processing import National, Base

In [5]:
nr = National()

## 2002

In [6]:
df_02 = pd.read_excel('data/nrsr/nrsr2002.xls')

In [7]:
df_02.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,Počet,Platné hlasy (počet/podiel),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\nOkres,platných\nhlasov\n spolu,SZS,SDKÚ,SDPO,SDĽ,SMER,HZDS,OKS,HZD,...,ANO,B-RRS,ŽAR,SDA,SNJ,NOSP,SNS,ROSA,ROISR,P SNS
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bratislava I,30501,258,12400,23,296,2707,3539,356,852,...,1639,10,71,946,39,93,929,19,1,325
4,NaN,NaN,0.84,40.65,0.07,0.97,8.87,11.6,1.16,2.79,...,5.37,0.03,0.23,3.1,0.12,0.3,3.04,0.06,0,1.06

In [8]:
df_02 = nr.preprocess_2002(df_02)

In [9]:
df_02 = Base.set_header_and_clean(df_02)

In [10]:
df_02 = nr.add_foreign(df_02)

In [11]:
df_02.head()

,Okres,platných hlasov spolu,SZS,SDKÚ,SDPO,SDĽ,SMER,HZDS,OKS,HZD,...,ANO,B-RRS,ŽAR,SDA,SNJ,NOSP,SNS,ROSA,ROISR,P SNS
0,Bratislava I,30501,258,12400,23,296,2707,3539,356,852,...,1639,10,71,946,39,93,929,19,1,325
1,Bratislava II,66134,586,22222,82,639,7737,8992,415,1997,...,4434,29,252,1832,61,207,2404,67,24,1053
2,Bratislava III,39825,388,13209,42,394,4889,5913,312,1256,...,2734,12,141,1092,64,153,1569,60,5,800
3,Bratislava IV,55082,505,20036,71,522,7196,6278,446,1611,...,4383,18,270,1739,74,208,1775,75,11,872
4,Bratislava V,72225,808,25795,84,746,9921,7467,554,1972,...,5816,29,396,2378,79,220,2413,80,21,1541

In [12]:
df_02.shape

(81, 27)

In [13]:
nr.process_a(df_02, 2002)

In [14]:
df_test = nr.df

In [15]:
df_test.head()

,election_year,election_type,district_id,district_name,total_district_votes,original_party_name,party_name,votes
0,2002,NR SR,<NA>,Bratislava I,30501,SZS,SZS,258
1,2002,NR SR,<NA>,Bratislava II,66134,SZS,SZS,586
2,2002,NR SR,<NA>,Bratislava III,39825,SZS,SZS,388
3,2002,NR SR,<NA>,Bratislava IV,55082,SZS,SZS,505
4,2002,NR SR,<NA>,Bratislava V,72225,SZS,SZS,808

## 2006

In [16]:
df_06 = pd.read_excel('data/nrsr/nrsr2006.xls')

In [17]:
df_06.head()

,"Počet a podiel platných hlasov odovzdaných pre politické strany podľa okresov, krajov a SR",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,Počet\nplatných\nhlasov\nspolu,Platné hlasy (počet / podiel),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"\nOkres, kraj,\nSR spolu",NaN,ĽB,S.O.S.,Misia 21,SDĽ,ZRS,KDH,SLNKO,ANO,...,OKS,PS,ĽS - HZDS,ASV,KSS,SĽS,SDKÚ - DS,SMER,SNS,NÁDEJ
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bratislava I,23 927,20,6,33,28,9,2 621,34,224,...,295,52,1 511,13,545,48,10 676,3 522,1 417,71
4,NaN,NaN,"0,08","0,02","0,13","0,11","0,03","10,95","0,14","0,93",...,"1,23","0,21","6,31","0,05","2,27","0,20","44,61","14,71","5,92","0,29"

In [18]:
df_06 = National.preprocess_2006(df_06)

In [19]:
df_06.head()

1,Okres,platných hlasov spolu,ĽB,S.O.S.,Misia 21,SDĽ,ZRS,KDH,SLNKO,ANO,...,OKS,PS,ĽS - HZDS,ASV,KSS,SĽS,SDKÚ - DS,SMER,SNS,NÁDEJ
3,Bratislava I,23 927,20,6,33,28,9,2 621,34,224,...,295,52,1 511,13,545,48,10 676,3 522,1 417,71
5,Bratislava II,53 581,62,27,50,92,55,3 945,109,659,...,289,123,3 784,60,1 540,99,19 958,10 860,4 168,228
7,Bratislava III,32 060,37,14,39,49,23,2 565,48,408,...,170,61,2 474,24,1 094,63,11 900,6 785,2 817,162
9,Bratislava IV,45 821,73,15,70,52,48,3 826,82,812,...,294,116,2 705,55,1 259,110,18 218,9 397,3 583,225
11,Bratislava V,58 211,75,17,42,100,63,4 138,108,932,...,403,208,3 006,52,1 586,153,22 012,12 925,4 907,253

In [20]:
df_06.shape

(80, 23)

In [21]:
df_06 = nr.add_foreign(df_06)

In [22]:
df_06.shape

(81, 23)

In [23]:
nr.process_a(df_06, 2006)

In [24]:
nr.df.shape

(1701, 8)

## 2010

In [25]:
df_10 = pd.read_excel('data/nrsr/nrsr2010.xls')

In [26]:
df_10.head()

,Kód\nokresu,Názov\nokresu,Počet\nvoleb.\nokrskov,Počet\nvoličov\nzapísaných\nv zoznamoch\nvoličov,"Počet\nvoličov,\nktorí sa\nzúčastnili\nna hlasovaní","Počet\nvoličov,\nktorí\nzaslali\nnávratnú\nobálku\nz cudziny","Počet\nvoličov,\nktorí\nhlasovali\nosobne",Počet\nplatných\nhlasov\nspolu,EDS,Únia,...,KSS,SNS,ND,ZRS,KDH,ĽSNS,SDKÚ - DS,AZEN,SMER,MOST - HÍD
0,101,Bratislava I,34,38113,25372,168,25188,25045,42,173,...,80,700,65,9,2739,95,8161,24,4738,2772
1,102,Bratislava II,107,97490,62356,213,62094,61750,104,682,...,237,2208,163,24,4666,345,17742,54,15136,5954
2,103,Bratislava III,64,54886,36477,137,36323,36097,61,303,...,173,1454,109,29,3090,209,10349,45,9310,2508
3,104,Bratislava IV,82,84085,54136,270,53806,53615,92,617,...,185,1765,144,41,4699,313,15738,79,12888,3924
4,105,Bratislava V,107,105818,64554,287,64229,64110,111,700,...,262,2325,186,43,4530,474,18882,82,15232,5133