In [1]:
import pandas as pd

# ep

In [2]:
from processing import Euro, Base

In [3]:
ep = Euro()

## 2004

In [4]:
df_04 = pd.read_excel('data/ep/ep2004.xlsx')

In [5]:
df_04 = Euro.preprocess_2004(df_04)

In [6]:
df_04.head()

,Okres,SMK-MKP,ANO,SDKÚ,MFS,ŽS SR,DÚ,KSS,SF,"SNS, P SNS",SĽS,AŽ-OS,SMER (tretia cesta),ĽS-HZDS,KDH,"HZD, ĽÚ",OKS,RKDH,Kód Okresu
3,Bratislava I,866,586,2 949,20,46,91,356,852,202,18,85,1 359,1 573,2 012,128,466,13,101.0
5,Bratislava II,1 963,979,4 751,26,95,55,679,1 152,373,13,149,3 005,3 225,2 807,192,398,11,102.0
7,Bratislava III,668,628,3 095,10,41,64,513,788,218,17,75,1 897,2 313,1 853,131,312,12,103.0
9,Bratislava IV,865,939,4 397,24,84,86,576,1 160,305,27,111,2 759,2 270,2 544,164,464,14,104.0
11,Bratislava V,1 279,1 203,4 610,19,106,92,645,1 262,360,29,173,3 604,2 054,2 696,211,501,28,105.0

In [7]:
ep.process_wide(df_04, 2004)

In [8]:
ep.df.head()

,election_year,election_type,district_id,district_name,original_party_name,party_name,votes
0,2004,EP,101,Bratislava I,SMK-MKP,SMK-MKP,866
1,2004,EP,102,Bratislava II,SMK-MKP,SMK-MKP,1963
2,2004,EP,103,Bratislava III,SMK-MKP,SMK-MKP,668
3,2004,EP,104,Bratislava IV,SMK-MKP,SMK-MKP,865
4,2004,EP,105,Bratislava V,SMK-MKP,SMK-MKP,1279

## 2009

In [9]:
df_09 = pd.read_excel('data/ep/ep2009.xls')

In [10]:
df_09.head()

,Počet a podiel platných hlasov odovzdaných pre politické strany podľa okresov,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Okres,Počet platných\nhlasov spolu,NaN,Platné hlasy (počet / podiel),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,ĽS-HZDS,NaN,SaS,NaN,SMER,NaN,SZ,...,SNS,NaN,LIGA,NaN,SDĽ,NaN,SF,NaN,KDH,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bratislava I,11 266,,592,,1 388,,2 211,,527,...,393,,40,,48,,173,,1 156,
4,NaN,NaN,,"5,25",,"12,32",,"19,62",,"4,67",...,"3,48",,"0,35",,"0,42",,"1,53",,"10,26",

In [11]:
df_09 = Euro.preprocess_2009(df_09)

In [12]:
df_09.head()

,Okres,ĽS-HZDS,SaS,SMER,SZ,SDKÚ- DS,DS,Misia 21,ASV,"KDS, OKS",SMK-MKP,KSS,SNS,LIGA,SDĽ,SF,KDH,Kód Okresu
3,Bratislava I,592,1 388,2 211,527,3 614,37,12,31,587,355,102,393,40,48,173,1 156,101.0
5,Bratislava II,1 418,2 252,6 401,947,6 743,71,18,59,794,1 380,192,963,64,115,377,1 803,102.0
7,Bratislava III,976,1 521,3 903,607,4 193,50,15,51,492,312,175,667,55,54,184,1 243,103.0
9,Bratislava IV,1 058,2 324,5 541,990,6 335,68,15,75,850,385,167,787,71,75,372,1 924,104.0
11,Bratislava V,1 043,2 430,5 690,1 048,6 458,74,17,89,887,626,161,961,57,144,480,1 708,105.0

In [13]:
ep.process_wide(df_09, 2009)

## 2014

In [14]:
df_14 = pd.read_excel('data/ep/ep2014.xlsx')

In [15]:
df_14.head()

,Počet a podiel platných hlasov odovzdaných pre politické subjekty podľa okresov a za Slovenskú republiku,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,"NOVA, Konzervatívni demokrati Slovenska, Občia...",NaN,Kresťanskodemokratické hnutie,NaN,SMER - sociálna demokracia,NaN,Slovenská ľudová strana,NaN,...,Strana občianskej ľavice,NaN,Slovenská národná strana,NaN,Slovenská demokratická a kresťanská únia - Dem...,NaN,"PRIAMA DEMOKRACIA, Kresťanská ľudová strana",NaN,Strana maďarskej komunity - Magyar Közösség Pá...,NaN
2,Okres,Počet platných\nhlasov spolu,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %,...,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %,Počet platných hlasov,Podiel platných hlasov v %
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bratislava I,8910,1662,18.65,933,10.47,1349,15.14,19,0.21,...,9,0.1,182,2.04,1546,17.35,45,0.5,84,0.94

In [16]:
df_14 = Euro.preprocess_2014(df_14)

In [17]:
df_14.head()

,Okres,"NOVA, Konzervatívni demokrati Slovenska, Občianska konzervatívna strana",Kresťanskodemokratické hnutie,SMER - sociálna demokracia,Slovenská ľudová strana,Národ a Spravodlivosť - naša strana,Magnificat Slovakia,DEMOKRATICKÁ OBČIANSKA STRANA,7 STATOČNÝCH REGIONÁLNA STRANA SLOVENSKA,Maďarská kresťanskodemokratická aliancia - Magyar Kereszténydemokrata Szövetség,...,Sloboda a Solidarita,Strana moderného Slovenska,Komunistická strana Slovenska,ÚSVIT,Strana občianskej ľavice,Slovenská národná strana,Slovenská demokratická a kresťanská únia - Demokratická strana,"PRIAMA DEMOKRACIA, Kresťanská ľudová strana",Strana maďarskej komunity - Magyar Közösség Pártja,Kód Okresu
4,Bratislava I,1662,933,1349,19,84,45,4,13,3,...,1149,39,86,17,9,182,1546,45,84,101.0
5,Bratislava II,2363,1729,3741,31,244,111,13,31,6,...,2155,48,170,39,14,548,2639,59,305,102.0
6,Bratislava III,1610,1090,2313,27,134,65,6,14,3,...,1379,20,105,19,4,404,1775,58,88,103.0
7,Bratislava IV,2338,1601,3188,32,248,79,11,29,5,...,2109,54,182,39,3,520,2570,62,87,104.0
8,Bratislava V,2086,1569,2963,42,241,125,13,33,7,...,2084,45,165,47,14,504,2360,95,187,105.0

In [18]:
ep.process_wide(df_14, 2014)

## 2019

In [19]:
df_19 = pd.read_excel('data/ep/ep2019.xlsx')

In [20]:
df_19.head()

,Počet a podiel platných hlasov odovzdaných pre politické subjekty za okresy,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kód kraja,Názov kraja,Kód územného obvodu,Názov územného obvodu,Kód okresu,Názov okresu,Číslo politického subjektu,Názov politického subjektu,Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné..."
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,1,SMER - sociálna demokracia,1004,6.45,807,80.37
4,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,2,Kresťanská demokracia - Život a prosperita,127,0.81,113,88.97

In [21]:
df_19 = Euro.preprocess_2020(df_19)

In [22]:
df_19.head()

1 Kód Okresu         Okres                                  party_name votes
3        101  Bratislava I                  SMER - sociálna demokracia  1004
4        101  Bratislava I  Kresťanská demokracia - Život a prosperita   127
5        101  Bratislava I      Kotleba - Ľudová strana Naše Slovensko   969
6        101  Bratislava I                     KOREKTÚRA - Andrej Hryc   145
7        101  Bratislava I                    Slovenská národná strana   411

In [23]:
ep.process_long(df_19, 2019)

## 2024

In [24]:
df_24 = pd.read_excel('data/ep/ep2024.xlsx')

In [25]:
df_24.head()

,Počet a podiel platných hlasov odovzdaných pre politické subjekty za okresy,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kód kraja,Názov kraja,Kód územného obvodu,Názov územného obvodu,Kód okresu,Názov okresu,Číslo politického subjektu,Názov politického subjektu,Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné..."
2,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,1,Slovenský PATRIOT,20,0.1,17,85
3,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,2,MySlovensko,1,0,0,0
4,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,3,Demokrati,1060,5.36,975,91.98

In [26]:
df_24 = Euro.preprocess_2020(df_24)

In [27]:
df_24.head()

1 Kód Okresu         Okres                            party_name votes
2        101  Bratislava I                     Slovenský PATRIOT    20
3        101  Bratislava I                           MySlovensko     1
4        101  Bratislava I                             Demokrati  1060
5        101  Bratislava I  Magyar Szövetség - Maďarská aliancia    74
6        101  Bratislava I      Spájame Občanov Slovenska - SOSK    15

In [28]:
ep.process_long(df_24, 2024)

In [29]:
ep.df.shape

(9295, 7)